[workspace]
members = ["kernel", "bootstrap", "shell", "libuser", "clock", "sm", "vi", "ahci", "libutils", "libkern"]

[profile.release]
debug = true

[profile.test]
debug = true

[patch.crates-io]
hashmap_core = { git = "https://github.com/pepyakin/hashmap_core", rev = "add-alloc-layout-extra" }
