[package]
name = "sunrise-libtimezone"
version = "0.1.0"
authors = ["Thog <contact@thog.eu>"]
edition = "2018"

[dependencies]
plain = "0.2.3"

[dependencies.num-traits]
version = "0.2"
default-features = false

[dependencies.static_assertions]
version  = "1.0.0"
features = ["nightly"]
